AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'aws-dict-sam

  Sample SAM Template for aws-dict-sam

  '
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*.ramakocherlakota.net'''
Resources:
  FillInBlanksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://dict-lambda-code/3f3f1a88916cff099be52e49ad098130
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        FillInBlanks:
          Type: Api
          Properties:
            Path: /fill-in-blanks
            Method: get
    Metadata:
      SamResourceId: FillInBlanksFunction
  AnagramFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://dict-lambda-code/fd863cb94be83abdf2f773fd546f6966
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:GetItem
          Resource: arn:aws:dynamodb:us-east-1:111144063151:table/anagram-data
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Anagram:
          Type: Api
          Properties:
            Path: /anagram
            Method: get
    Metadata:
      SamResourceId: AnagramFunction
  PangramFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://dict-lambda-code/8a9abe43647d799b408349b4e90ccfba
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:GetItem
          Resource: arn:aws:dynamodb:us-east-1:111144063151:table/pangram-data
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Pangram:
          Type: Api
          Properties:
            Path: /pangram
            Method: get
    Metadata:
      SamResourceId: PangramFunction
Outputs:
  FillInBlanksApi:
    Description: API Gateway endpoint URL for Prod stage for FillInBlanks function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fill-in-blanks/
  FillInBlanksFunction:
    Description: Fill In Blanks Lambda Function ARN
    Value:
      Fn::GetAtt:
      - FillInBlanksFunction
      - Arn
  FillInBlanksFunctionIamRole:
    Description: Implicit IAM Role created for Fill In Blanks function
    Value:
      Fn::GetAtt:
      - FillInBlanksFunctionRole
      - Arn
  AnagramApi:
    Description: API Gateway endpoint URL for Prod stage for Anagram function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/anagram/
  AnagramFunction:
    Description: Anagram Lambda Function ARN
    Value:
      Fn::GetAtt:
      - AnagramFunction
      - Arn
  AnagramFunctionIamRole:
    Description: Implicit IAM Role created for Anagram function
    Value:
      Fn::GetAtt:
      - AnagramFunctionRole
      - Arn
  PangramApi:
    Description: API Gateway endpoint URL for Prod stage for Pangram function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pangram/
  PangramFunction:
    Description: Pangram Lambda Function ARN
    Value:
      Fn::GetAtt:
      - PangramFunction
      - Arn
  PangramFunctionIamRole:
    Description: Implicit IAM Role created for Pangram function
    Value:
      Fn::GetAtt:
      - PangramFunctionRole
      - Arn
