AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    aws-dict-sam

    Sample SAM Template for aws-dict-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3


Resources:

    FillInBlanksFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: fill-in-blanks/
            Handler: app.lambda_handler
            Runtime: python3.7
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                FillInBlanks:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /fill-in-blanks
                        Method: get

    AnagramFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: anagram/
            Policies:
              - AWSLambdaExecute
              - Version: '2012-10-17' # Policy Document
                Statement:
                  - Effect: Allow
                    Action:
                      - dynamodb:GetItem
                    Resource: 'arn:aws:dynamodb:us-east-1:111144063151:table/anagram-data'
            Handler: app.lambda_handler
            Runtime: python3.7
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                Anagram:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /anagram
                        Method: get

#    AnagramDataTable:
#      Type: AWS::DynamoDBTable
#      BillingMode: "PAY_PER_REQUEST"
#      TableName: "anagram-data"
#      Properties:
#        KeySchema:
#          -
#            AttributeName: "id"
#            KeyType: "HASH"
#        AttributeDefintions:
#          -
#            AttributeName: "id"
#            AttibuteType: "S"
#          -
#            AttributeName: "words"
#            AttributeType: "SS"
                
Outputs:

    FillInBlanksApi:
      Description: "API Gateway endpoint URL for Prod stage for FillInBlanks function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fill-in-blanks/"

    FillInBlanksFunction:
      Description: "Fill In Blanks Lambda Function ARN"
      Value: !GetAtt FillInBlanksFunction.Arn

    FillInBlanksFunctionIamRole:
      Description: "Implicit IAM Role created for Fill In Blanks function"
      Value: !GetAtt FillInBlanksFunctionRole.Arn


    AnagramFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: anagram/
            Handler: app.lambda_handler
            Runtime: python3.7
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                Anagram:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /anagram
                        Method: get

    AnagramApi:
      Description: "API Gateway endpoint URL for Prod stage for Anagram function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/anagram/"

    AnagramFunction:
      Description: "Anagram Lambda Function ARN"
      Value: !GetAtt AnagramFunction.Arn

    AnagramFunctionIamRole:
      Description: "Implicit IAM Role created for Anagram function"
      Value: !GetAtt AnagramFunctionRole.Arn

